### ISSUE TITLE
Why use @charset?

### ISSUE THREAD

**Issue by TKDev7** [chriskirknielsen/chriskirknielsen.com#1]
Hi Chris 👋! I have noticed you have a @charset rule in your base css file and I was wondering why. I thought the meta tag with charset attribute should be enough. Thanks!

Fantastic website btw!

**Comment by chriskirknielsen** [comment]
Hi @MrHBS and thank you for your kind words!

That's a good catch, this is legacy stuff that's been carried around my codebase [since at least 2018](https://github.com/chriskirknielsen/2018/blob/master/scss/critical.scss).

Fixed with #2 — thanks!
